/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.martin.doceMonedas.gui;

import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.martin.doceMonedas.base.Player;
import org.martin.doceMonedas.base.TwelveCoins;

/**
 *
 * @author martin
 */
public class GUITwelveCoins extends javax.swing.JFrame {

    private static final byte ENTER_KEY = KeyEvent.VK_ENTER;
    private TwelveCoins twelveCoins;
    
    public GUITwelveCoins() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(397, 227);
        setResizable(false);
        formGame.setSize(formGame.getPreferredSize());
        formGame.setLocationRelativeTo(null);
        formGame.setResizable(false);
        dialogHelp.setSize(dialogHelp.getPreferredSize());
        dialogHelp.setLocationRelativeTo(formGame);
        formGame.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formGame = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblCurrentPlayer = new javax.swing.JLabel();
        panelGame = new javax.swing.JPanel();
        lbl0 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        btnSetTurn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        itemHelp = new javax.swing.JMenuItem();
        dialogHelp = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPlayer1 = new javax.swing.JTextField();
        txtPlayer2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnStartGame = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del juego"));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel5.setText("Juega: ");

        lblCurrentPlayer.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCurrentPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblCurrentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelGame.setBackground(new java.awt.Color(255, 255, 255));
        panelGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl0.setOpaque(true);
        lbl0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl0MouseReleased(evt);
            }
        });
        panelGame.add(lbl0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 77, 78));

        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl4.setOpaque(true);
        lbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl4MouseReleased(evt);
            }
        });
        panelGame.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 77, 78));

        lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl6.setOpaque(true);
        lbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl6MouseReleased(evt);
            }
        });
        panelGame.add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 77, 78));

        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl1.setOpaque(true);
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl1MouseReleased(evt);
            }
        });
        panelGame.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 77, 78));

        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl2.setOpaque(true);
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl2MouseReleased(evt);
            }
        });
        panelGame.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 77, 78));

        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl3.setOpaque(true);
        lbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl3MouseReleased(evt);
            }
        });
        panelGame.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 77, 78));

        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl5.setOpaque(true);
        lbl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl5MouseReleased(evt);
            }
        });
        panelGame.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 77, 78));

        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl11.setOpaque(true);
        lbl11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl11MouseReleased(evt);
            }
        });
        panelGame.add(lbl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 77, 78));

        lbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl10.setOpaque(true);
        lbl10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl10MouseReleased(evt);
            }
        });
        panelGame.add(lbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 77, 78));

        lbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl9.setOpaque(true);
        lbl9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl9MouseReleased(evt);
            }
        });
        panelGame.add(lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 77, 78));

        lbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl8.setOpaque(true);
        lbl8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl8MouseReleased(evt);
            }
        });
        panelGame.add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 77, 78));

        lbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/martin/doceMonedas/resources/coin 128-128.png"))); // NOI18N
        lbl7.setOpaque(true);
        lbl7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl7MouseReleased(evt);
            }
        });
        panelGame.add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 77, 78));

        btnSetTurn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnSetTurn.setText("Terminar Turno");
        btnSetTurn.setToolTipText("Haga click cuando finalice su turno solo si ha eliminado una sola moneda");
        btnSetTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetTurnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Game");

        itemHelp.setText("Help");
        itemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHelpActionPerformed(evt);
            }
        });
        jMenu2.add(itemHelp);

        jMenuBar1.add(jMenu2);

        formGame.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout formGameLayout = new javax.swing.GroupLayout(formGame.getContentPane());
        formGame.getContentPane().setLayout(formGameLayout);
        formGameLayout.setHorizontalGroup(
            formGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formGameLayout.createSequentialGroup()
                        .addGroup(formGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelGame, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSetTurn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formGameLayout.setVerticalGroup(
            formGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSetTurn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGame, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(1);
        jTextArea2.setTabSize(4);
        jTextArea2.setText("Debe eliminar una moneda haciendo click, \npuede eliminar como máximo dos siempre\ny cuando éstas sean contiguas. El jugador\nque elimina la última moneda gana el\njuego.");
        jTextArea2.setOpaque(true);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reglas del juego");

        javax.swing.GroupLayout dialogHelpLayout = new javax.swing.GroupLayout(dialogHelp.getContentPane());
        dialogHelp.getContentPane().setLayout(dialogHelpLayout);
        dialogHelpLayout.setHorizontalGroup(
            dialogHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dialogHelpLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        dialogHelpLayout.setVerticalGroup(
            dialogHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(397, 197));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugadores"));

        jLabel2.setText("Jugador 1: ");

        txtPlayer1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlayer1KeyReleased(evt);
            }
        });

        txtPlayer2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlayer2KeyReleased(evt);
            }
        });

        jLabel3.setText("Jugador 2: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido a Doce Monedas");

        btnStartGame.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnStartGame.setText("Comenzar");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartGame)
                    .addComponent(btnExit))
                .addGap(145, 145, 145))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlayer1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlayer1KeyReleased
        if (evt.getKeyCode() == ENTER_KEY) {
            txtPlayer2.requestFocus();
            txtPlayer2.selectAll();
        }
    }//GEN-LAST:event_txtPlayer1KeyReleased

    private void txtPlayer2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlayer2KeyReleased
        if (evt.getKeyCode() == ENTER_KEY)
            btnStartGame.doClick();
        
    }//GEN-LAST:event_txtPlayer2KeyReleased

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        final String name1 = txtPlayer1.getText().trim();
        final String name2 = txtPlayer2.getText().trim();
        
        if (name1.isEmpty() || name2.isEmpty()) 
            JOptionPane.showMessageDialog(this, "Debe ingresar el nombre de ambos jugadores");
        
        else{
            twelveCoins = new TwelveCoins(new Player(name1), new Player(name2, false));
            twelveCoins.builtCoins(btnSetTurn, lbl0, lbl1, lbl2, lbl3, lbl4, lbl5, 
                    lbl6, lbl7, lbl8, lbl9, lbl10, lbl11);
            twelveCoins.drawAll();
            hide();
            formGame.show();
            lblCurrentPlayer.setText(twelveCoins.getPlayerNameIsPlaying());
        }
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void itemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHelpActionPerformed
        dialogHelp.show();
    }//GEN-LAST:event_itemHelpActionPerformed

    private void lbl1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseReleased
        execCoinEvent(1);
    }//GEN-LAST:event_lbl1MouseReleased

    private void btnSetTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetTurnActionPerformed
        setTurn();
    }//GEN-LAST:event_btnSetTurnActionPerformed

    private void lbl2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseReleased
        execCoinEvent(2);
    }//GEN-LAST:event_lbl2MouseReleased

    private void lbl0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl0MouseReleased
        execCoinEvent(0);
    }//GEN-LAST:event_lbl0MouseReleased

    private void lbl3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseReleased
        execCoinEvent(3);
    }//GEN-LAST:event_lbl3MouseReleased

    private void lbl4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl4MouseReleased
        execCoinEvent(4);
    }//GEN-LAST:event_lbl4MouseReleased

    private void lbl5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl5MouseReleased
        execCoinEvent(5);
    }//GEN-LAST:event_lbl5MouseReleased

    private void lbl6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl6MouseReleased
        execCoinEvent(6);
    }//GEN-LAST:event_lbl6MouseReleased

    private void lbl7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl7MouseReleased
        execCoinEvent(7);
    }//GEN-LAST:event_lbl7MouseReleased

    private void lbl8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl8MouseReleased
        execCoinEvent(8);
    }//GEN-LAST:event_lbl8MouseReleased

    private void lbl9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl9MouseReleased
        execCoinEvent(9);
    }//GEN-LAST:event_lbl9MouseReleased

    private void lbl10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl10MouseReleased
        execCoinEvent(10);
    }//GEN-LAST:event_lbl10MouseReleased

    private void lbl11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl11MouseReleased
        execCoinEvent(11);
    }//GEN-LAST:event_lbl11MouseReleased

    private void execCoinEvent(int index){
        final JLabel lbl;
        switch(index){
            case 0:
                lbl = lbl0;
                break;
                
            case 1:
                lbl = lbl1;
                break;
                
            case 2:
                lbl = lbl2;
                break;
                
            case 3:
                lbl = lbl3;
                break;
                
            case 4:
                lbl = lbl4;
                break;
                
            case 5:
                lbl = lbl5;
                break;
                
            case 6:
                lbl = lbl6;
                break;
                
            case 7:
                lbl = lbl7;
                break;
                
            case 8:
                lbl = lbl8;
                break;
                
            case 9:
                lbl = lbl9;
                break;
                
            case 10:
                lbl = lbl10;
                break;
                
            default:
                lbl = lbl11;
                break;
        }
        
        if (lbl.isVisible()){
            final int playsFollowed = twelveCoins.getPlaysFollowed();
            if (playsFollowed == 0) 
                btnSetTurn.setEnabled(true);
            
            if (playsFollowed < 2){
                twelveCoins.deleteCoin(index);
                testWinner();
                if (twelveCoins.getPlaysFollowed() == 2) setTurn();
            }
            else
                JOptionPane.showMessageDialog(this, "Ha alcanzado el límite de jugadas seguidas");
        }
    }
    
    private void testWinner(){
        if (twelveCoins.hasWinner()) {
            formGame.setEnabled(false);
            JOptionPane.showMessageDialog(formGame, "¡Juego terminado!\nHa ganado "
                    + twelveCoins.getPlayerNameWinner());
            System.exit(0);
        }
    }
    
    private void setTurn(){
        btnSetTurn.setEnabled(false);
        twelveCoins.setTurn();
        lblCurrentPlayer.setText(twelveCoins.getPlayerNameIsPlaying());
        testWinner();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITwelveCoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITwelveCoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITwelveCoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITwelveCoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITwelveCoins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSetTurn;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JDialog dialogHelp;
    private javax.swing.JFrame formGame;
    private javax.swing.JMenuItem itemHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lbl0;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblCurrentPlayer;
    private javax.swing.JPanel panelGame;
    private javax.swing.JTextField txtPlayer1;
    private javax.swing.JTextField txtPlayer2;
    // End of variables declaration//GEN-END:variables
}
